Models/DTO/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace MovieStore.Models.DTO
{
    public class LoginModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*[#$^+=!*()@%&]).{6,}$", ErrorMessage = "Minímo de 6 caracteres deve conter 1 Letra Maiúscula, 1 Minúscula, 1 caracter especial")]
        public string Password { get; set; }
    }
}

Models/DTO/RegistrationModel.cs
using System.ComponentModel.DataAnnotations;

namespace MovieStore.Models.DTO
{
    public class RegistrationModel
    {
        [Required]
        public string? Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string UserName { get; set; }

        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*[#$^+=!*()@%&]).{6,}$", ErrorMessage = "Minímo de 6 caracteres deve conter 1 Letra Maiúscula, 1 Minúscula, 1 caracter especial")]
        public string Password { get; set; }

        [Required]
        [Compare("Password")]
        public string PasswordConfirm { get; set; }
        public string Role { get; set; }
    }
}

Models/DTO/Status.cs
namespace MovieStore.Models.DTO
{
    public class Status
    {
        public int StatusCode { get; set; }
        public string? Message { get; set; }
    }
}

Models/Domains/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace MovieStore.Models.Domains
{
    public class ApplicationUser : IdentityUser
    {
        public string? Name { get; set; }
    }
}

Models/Domains/DatabaseContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace MovieStore.Models.Domains
{
    public class DatabaseContext : IdentityDbContext<ApplicationUser>
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options){ }

        public DbSet<MovieGenre>? MovieGenre { get; set; }
        public DbSet<Genre>? Genre { get; set; }
        public DbSet<Movie>? Movie { get; set; }
    }
}

Models/Domains/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace MovieStore.Models.Domains
{
    public class Genre
    {
        public int Id { get; set; }

        [Required]
        public string? GenreName { get; set; }
    }
}

Models/Domains/Movie.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieStore.Models.Domains
{
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        public string? Title { get; set; }
        public string? ReleaseYear { get; set; }
        public string? MovieImage { get; set; }

        [Required]
        public string? Cast { get; set; }
        public string? Director { get; set; }

        [NotMapped]
        public IFormFile? ImageFile { get; set; }

        [NotMapped]
        [Required]
        public List<int>? Genre { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem>? GenreList { get; set; }

        [NotMapped]
        public int GenreNames { get; set; }

        [NotMapped]
        public MultiSelectList? MultiSelectList { get; set; }
    }
}

Models/Domains/MovieGenre.cs
namespace MovieStore.Models.Domains
{
    public class MovieGenre
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int GenreId { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MovieStore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStore.Models.Domains;
using MovieStore.Repositories.Abstract;
using MovieStore.Repositories.Implementation;

namespace MovieStore.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreServices _genreService;
        public GenreController(IGenreServices genreServices)
        {
            _genreService = genreServices;
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Genre model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = _genreService.Add(model);
            if (result)
            {
                TempData["msg"] = "Adicionado com sucesso";
                return RedirectToAction(nameof(Add));
            }
            else
            {
                TempData["msg"] = "Erro no servidor";
                return View(model);
            }
        }

        public IActionResult Edit(int id)
        {
            var data = _genreService.GetById(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Update(Genre model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = _genreService.Update(model);
            if (result)
            {
                TempData["msg"] = "Adicionar com sucesso";
                return RedirectToAction(nameof(GenreList));
            }
            else
            {
                TempData["msg"] = "Err ono servidor";
                return View(model);
            }
        }

        public IActionResult GenreList()
        {
            var data = this._genreService.GetAll().ToList();
            return View(data);
        }

        public IActionResult Delete(int id)
        {
            var result = _genreService.Delete(id);
            return RedirectToAction(nameof(GenreList));
        }



    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieStore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/UserAuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStore.Models.DTO;
using MovieStore.Repositories.Abstract;

namespace MovieStore.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private readonly IUserAuthenticationServices _userAuthenticationServices;
        public UserAuthenticationController(IUserAuthenticationServices userAuthenticationServices)
        {
            _userAuthenticationServices = userAuthenticationServices;
        }
        public async Task<IActionResult> Register()
        {
            var model = new RegistrationModel()
            {
                Email = "admin@gmail.com",
                UserName = "Admin",
                Name = "Cassio",
                Password = "Admin@1234",
                PasswordConfirm = "Admin@1234",
                Role = "Admin"
            };
            var result = await _userAuthenticationServices.RegisterAsync(model);
            return Ok(result.Message);
        }

        public async Task<IActionResult> Login()
        {       
             return View();            
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel login)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }
            var result = await _userAuthenticationServices.LoginAsync(login);
            if(result.StatusCode == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = "Erro ao tentar logar!";
                return RedirectToAction(nameof(Login));
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _userAuthenticationServices.LogoutAsync();

            return RedirectToAction(nameof(Login));
        }
    }
}

Views/Genre/Add.cshtml
@model MovieStore.Models.Domains.Genre

@{
}

<form asp-controller="Genre" asp-action="Add" method="post">
    <h2>Add Genre</h2>
    User Name <input asp-for="GenreName" type="text"/><br />
    <span asp-validation-for="GenreName"></span>

    @if (TempData["msg"] != null)
    {
            <div class="alert mb-1">
            @TempData["msg"]
            </div>
    }
    <button class="btn btn-primary" type="submit">Login</button>
</form>

Views/Home/About.cshtml
@{
    
}

<h2>About</h2>

<p>Comming soon...</p>

Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
<section class="search-bar">
    <form>
        <input type="text" placeholder="search here">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</section>
<section class="movies">
    <div class="movie-card" onclick="window.location.href='/movie-detail.html'">
        <div class="movie-image">
            <img src="https://picsum.photos/id/1/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 1</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>

    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 3</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max,anna, ralph, dorian </h4>
            <h4>director 1,director 2,director 3</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>



    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>


    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>

    <div class="movie-card">
        <div class="movie-image">
            <img src="https://picsum.photos/id/237/200/300">
        </div>
        <div class="movie-info">
            <h4>Movie 2</h4>
            <h4>Action, Adventure</h4>
            <h4>John doe, max </h4>
            <h4>director 1</h4>
        </div>
    </div>
</section>

<div class="pagination">
    <a href="#">&laquo;</a>
    <a href="#">1</a>
    <a class="active" href="#">2</a>
    <a href="#">3</a>
    <a href="#">4</a>
    <a href="#">5</a>
    <a href="#">6</a>
    <a href="#">&raquo;</a>
</div>

Views/Shared/_Layout.cshtml
@{
    string userName = User.Identity.Name;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie store</title>
<link rel="stylesheet" href="/css/site.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="/images/movie_filter_FILL0_wght400_GRAD0_opsz48.svg">
    <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@500&display=swap" rel="stylesheet">
</head>
<body>

    <nav class="nav-bar">
        <div class="Logo">
            Movie Store
        </div>
        <ul class="nav-link">
            <li><a class="active" asp-controller="Home" asp-action="Index">Home</a></li>
            <li><a asp-controller="Home" asp-action="About">About</a></li>
            @if (User.IsInRole("Admin"))
            {          
                    <li>
                        <a href="#">Admin <i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-nav-link">
                             <li><a asp-controller="Genre" asp-action="Add">Add Genre</a></li>
                             <li><a asp-controller="UserAuthentication" asp-action="Logout">Logout</a></li>
                        </ul>
                    </li>
            }
            @if(!User.Identity.IsAuthenticated){

                <li><a asp-controller="UserAuthentication" asp-action="Login">Login</a></li>
            }
        </ul>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <footer>
        2023 - AppMovieStore - Cassio Fialho Lima
    </footer>
</body>

Views/UserAuthentication/Login.cshtml
@model MovieStore.Models.DTO.LoginModel
@{
    
}

<form asp-controller="UserAuthentication" asp-action="Login" method="post">
    <h2>Login</h2>
    User Name <input asp-for="Name" type="text"/><br />
    <span asp-validation-for="Name"></span>
    <br />
    Password <input asp-for="Password"type="text"/><br />
    <span asp-validation-for="Password"></span>

    @if(TempData["msg"] != null){
        <div class="alert mb-1">
            @TempData["msg"]
        </div>
    }
    <button class="btn btn-primary" type="submit">Login</button>
</form>